name: Test platform creation
on: push
jobs:
  tests:
    strategy:
      matrix:
        fail-fast: false
        version: ["main", "stable"]
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install qibolab stable
        if: ${{ matrix.version == 'stable' }}
        run: |
          python -m venv testenv
          source testenv/bin/activate
          pip install pytest
          pip install qcodes qibolab-qm qibolab-qblox
      - name: Install and configure poetry
        if: ${{ matrix.version == 'main' }}
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install qibolab main
        if: ${{ matrix.version == 'main' }}
        run: |
          python -m venv testenv
          source testenv/bin/activate
          for lib in qibolab-qm qibolab-qblox qibolab
          do
            git clone https://github.com/qiboteam/$lib
            cd $lib
            poetry install --no-interaction --with tests --all-extras
            cd ..
          done
      - name: Test platforms
        run: |
          source testenv/bin/activate
          QIBOLAB_PLATFORMS=$(realpath .) pytest _tests/
